apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-qwen3-32b
  namespace: inference
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 80Gi
